#!/usr/bin/env ruby

require_relative "lib/audition"
require_relative "lib/directory"
require_relative "lib/sort"

if ARGV[0] == "sort"
  ARGV.shift
  sort "lexicon.txt"
  exit 0
end

puts Audition.new(Directory.new(".")).run
