#!/bin/bash

prev=""

for arg in "$@"; do
  case "${prev: -1}" in
    a|e|i|o|u|d|b|g|l|r|n|m)
      "$(dirname "$0")/lib/lenit.sh" "$arg"
      prev="$arg"
      ;;
    *)
      echo -n "$arg"
      prev="$arg"
      ;;
  esac
done
